_target_: pvnet.data.UKRegionalPresavedDataModule

# The sample_dir is the location batches were saved to using the save_samples.py script
# The sample_dir should contain train and val subdirectories with samples

sample_dir: "PLACEHOLDER"
num_workers: 10
prefetch_factor: 2
batch_size: 8
