_target_: pvnet.data.UKRegionalStreamedDataModule
# Path to the data configuration yaml file. You can find examples in the configuration subdirectory
# in configs.example/datamodule/configuration
# Use the full local path such as: /FULL/PATH/PVNet/configs/datamodule/configuration/example_configuration.yaml"
configuration: "PLACEHOLDER.yaml"
num_workers: 20
prefetch_factor: 2
batch_size: 8

train_period:
  - null
  - "2022-05-07"
val_period:
  - "2022-05-08"
  - "2023-05-08"
