_target_: pvnet.models.multimodal.multimodal.Model

output_quantiles: [0.02, 0.1, 0.25, 0.5, 0.75, 0.9, 0.98]

#--------------------------------------------
# NWP encoder
#--------------------------------------------
nwp_encoders_dict:
  ecmwf:
    _target_: pvnet.models.multimodal.encoders.encoders3d.DefaultPVNet
    _partial_: True
    in_channels: 14
    out_features: 256
    number_of_conv3d_layers: 6
    conv3d_channels: 32
    image_size_pixels: 16

#--------------------------------------------
# Sensor encoder settings
#--------------------------------------------

wind_encoder:
  _target_: pvnet.models.multimodal.site_encoders.encoders.SingleAttentionNetwork
  _partial_: True
  num_sites: 19
  out_features: 40
  num_heads: 4
  kdim: 40
  id_embed_dim: 20

#--------------------------------------------
# Tabular network settings
#--------------------------------------------

output_network:
  _target_: pvnet.models.multimodal.linear_networks.networks.ResFCNet2
  _partial_: True
  fc_hidden_features: 128
  n_res_blocks: 6
  res_block_layers: 2
  dropout_frac: 0.0

embedding_dim: 16
include_sun: False
include_gsp_yield_history: False

# The mapping between the location IDs and their embedding indices
location_id_mapping:
  1: 1
  5: 2
  110: 3
# ...

#--------------------------------------------
# Times
#--------------------------------------------

# Foreast and time settings
forecast_minutes: 480
history_minutes: 120

min_sat_delay_minutes: 60

# --- set to null if same as history_minutes ---
sat_history_minutes: 90
nwp_history_minutes: 60
nwp_forecast_minutes: 2880
pv_history_minutes: 180
pv_interval_minutes: 15
sat_interval_minutes: 15

target_key: "sensor"
# ----------------------------------------------
# Optimizer
# ----------------------------------------------
optimizer:
  _target_: pvnet.optimizers.EmbAdamWReduceLROnPlateau
  lr: 0.0001
  weight_decay: 0.01
  amsgrad: True
  patience: 5
  factor: 0.1
  threshold: 0.002
