# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: late_fusion.yaml
  - datamodule: premade_samples.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: wandb.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - experiment: null
  - hparams_search: null
  - hydra: default.yaml

renewable: "pv_uk"

# enable color logging
#  - override hydra/hydra_logging: colorlog
#  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

model_name: "default"

# pretty print config at the start of the run using Rich library
print_config: True

seed: 2727831
