_target_: pvnet.data.datamodule.DataModule
configuration: null
# The batch_dir is the location batches were saved to using the save_batches.py script
# The batch_dir should contain train and val subdirectories with batches
batch_dir: /mnt/disks/sukh-pvnet-research-1/pvnet_batches
num_workers: 4
prefetch_factor: 2
batch_size: 32