general:
  description: Example config for producing PVNet samples for a reneweble generation site
  name: site_example_config

input_data:

  site:
    time_resolution_minutes: 15
    interval_start_minutes: -60
    interval_end_minutes: 480
    file_path: PLACEHOLDER.nc
    metadata_file_path: PLACEHOLDER.csv
    dropout_timedeltas_minutes: null
    dropout_fraction: 0 # Fraction of samples with dropout

  nwp:
    ecmwf:
      provider: ecmwf
      # Path to ECMWF NWP data in zarr format
      # n.b. It is not necessary to use multiple or any NWP data. These entries can be removed
      zarr_path: PLACEHOLDER
      interval_start_minutes: -60
      interval_end_minutes: 480
      time_resolution_minutes: 60
      channels:
        - t2m # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - tcc # total cloud cover
        - sde # snow depth water equivalent
        - sr # direct solar radiation
        - duvrs # downwards UV radiation at surface
        - prate # precipitation rate
        - u10 # 10-metre U component of wind speed
        - u100 # 100-metre U component of wind speed
        - u200 # 200-metre U component of wind speed
        - v10 # 10-metre V component of wind speed
        - v100 # 100-metre V component of wind speed
        - v200 # 200-metre V component of wind speed
      image_size_pixels_height: 24
      image_size_pixels_width: 24
      dropout_timedeltas_minutes: [-360]
      dropout_fraction: 1.0
      max_staleness_minutes: null

  satellite:
    zarr_path: PLACEHOLDER.zarr
    interval_start_minutes: -30
    interval_end_minutes: 0
    time_resolution_minutes: 5
    channels:
      # Uses for each channel taken from https://resources.eumetrain.org/data/3/311/bsc_s4.pdf
      - IR_016 # Surface, cloud phase
      - IR_039 # Surface, clouds, wind fields
      - IR_087 # Surface, clouds, atmospheric instability
      - IR_097 # Ozone
      - IR_108 # Surface, clouds, wind fields, atmospheric instability
      - IR_120 # Surface, clouds, atmospheric instability
      - IR_134 # Cirrus cloud height, atmospheric instability
      - VIS006 # Surface, clouds, wind fields
      - VIS008 # Surface, clouds, wind fields
      - WV_062 # Water vapor, high level clouds, upper air analysis
      - WV_073 # Water vapor, atmospheric instability, upper-level dynamics
    image_size_pixels_height: 24
    image_size_pixels_width: 24
    dropout_timedeltas_minutes: null
    dropout_fraction: 0.
