name: Pull CI (Python)
run-name: 'Test PR edit #${{ github.event.number }} "${{ github.event.pull_request.title }}"'

on:
  pull_request:
    paths-ignore: ['README.md']

jobs:

  pull-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    if: ${{ github.event.pull_request.head.repo.fork }}
    with:
      enable_linting: true
      enable_typechecking: false
      containerfile: 'None'
      tests_folder: 'tests'
      tests_matrix: true
