name: Tagged CI
run-name: 'Tagged CI for ${{ github.ref_name }} by ${{ github.actor }}'

on:
  push:
    tags: ["v*.*.*"]

jobs:
  tagged-ci:
    uses: openclimatefix/.github/.github/workflows/tagged_ci.yml@main
    secrets: inherit
    with:
      containerfile: 'None'
      enable_pypi: true
