name: Test and release

on:
  push
#  push:
#    branches:
#      - main

jobs:
  test:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      # 0 means don't use pytest-xdist
      pytest_numcpus: "4"
      # pytest-cov looks at this folder
      pytest_cov_dir: "pvnet"
      # extra things to install
      sudo_apt_install: "libgeos++-dev libproj-dev proj-data proj-bin"
      #      brew_install: "proj geos librttopo"
      os_list: '["ubuntu-latest"]'

  release:
    needs: test
    uses: openclimatefix/.github/.github/workflows/python-docker-release.yml@main
    secrets:
      token: ${{ secrets.PYPI_API_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

