name: Test and release

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Check files with pre-commit
      run: |
        pre-commit run --all-files

    - name: Pytest
      run: |
        pytest -s --cov=predict_pv_yield

  release:
    needs: test
    uses:  openclimatefix/.github/.github/workflows/python-release.yml@main
    secrets:
      token: ${{ secrets.token }}
